/**
 * Copies browser-side vendor library bundles from node_modules to assets/js/vendor/.
 * Runs automatically via the `prebuild` npm hook before every build.
 *
 * Libraries copied:
 *   pdf-lib  (MIT)          — PDF creation and manipulation
 *   pdfjs-dist (Apache 2.0) — PDF rendering (page to canvas)
 *   js-yaml  (MIT)          — YAML parse/stringify for developer tools
 *   jsqr     (MIT)          — QR code decoding from image data
 *   jsbarcode (MIT)         — Barcode generation (Code128, EAN, UPC, etc.)
 *   qrcode   (MIT)          — QR code generation (pre-bundled IIFE, see note)
 *
 * All bundles are self-contained (zero top-level imports) and served as plain
 * static files from /assets/js/vendor/ — no external CDN dependencies.
 *
 * Note: qrcode does not ship a pre-built browser bundle. The file at
 * assets/js/vendor/qrcode.min.js is generated by esbuild (see package.json
 * prebuild-dev script). Rebuild it after upgrading qrcode version.
 */

import { copyFile, mkdir } from 'fs/promises';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root      = path.join(__dirname, '..');
const vendor    = path.join(root, 'assets', 'js', 'vendor');
const nm        = path.join(root, 'node_modules');

await mkdir(vendor, { recursive: true });

const copies = [
  // pdf-lib ESM bundle (self-contained)
  [path.join(nm, 'pdf-lib', 'dist', 'pdf-lib.esm.js'),
   path.join(vendor, 'pdf-lib.esm.js')],

  // pdfjs-dist main module + worker (both self-contained)
  [path.join(nm, 'pdfjs-dist', 'build', 'pdf.mjs'),
   path.join(vendor, 'pdfjs.mjs')],

  [path.join(nm, 'pdfjs-dist', 'build', 'pdf.worker.mjs'),
   path.join(vendor, 'pdfjs.worker.mjs')],

  // Developer tool libraries — self-hosted to eliminate CDN dependency
  [path.join(nm, 'js-yaml', 'dist', 'js-yaml.min.js'),
   path.join(vendor, 'js-yaml.min.js')],

  [path.join(nm, 'jsqr', 'dist', 'jsQR.js'),
   path.join(vendor, 'jsQR.js')],

  [path.join(nm, 'jsbarcode', 'dist', 'JsBarcode.all.min.js'),
   path.join(vendor, 'JsBarcode.all.min.js')],

  // qrcode.min.js is pre-built by esbuild and already in assets/js/vendor/
  // so no copy needed here.
];

for (const [src, dst] of copies) {
  await copyFile(src, dst);
}

console.log('  ✓ Vendor files copied to assets/js/vendor/');
